# Generated by Django 5.2 on 2025-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='main',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
