# Generated by Django 5.2 on 2025-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_forms_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='optionRaw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
