# Generated by Django 5.2 on 2025-04-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formfields_optionraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='forms',
            field=models.ManyToManyField(related_name='subjects', to='forms.forms'),
        ),
    ]
