# Generated by Django 5.2 on 2025-04-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_subject_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='forms',
        ),
        migrations.AddField(
            model_name='forms',
            name='subjects',
            field=models.ManyToManyField(related_name='forms', to='forms.subject'),
        ),
    ]
