# Generated by Django 5.2 on 2025-04-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_subject_forms_forms_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='forms', to='forms.subject'),
        ),
    ]
