# Generated by Django 5.2 on 2025-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_forms_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='forms', to='forms.subject'),
        ),
    ]
