# Generated by Django 5.2 on 2025-04-22 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_forms_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfields',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formfields', to='forms.forms'),
        ),
    ]
