# Generated by Django 5.2 on 2025-04-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_formfields_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.forms')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.subject')),
            ],
            options={
                'unique_together': {('form', 'subject')},
            },
        ),
    ]
