# Generated by Django 5.2 on 2025-04-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_formsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='subjects',
        ),
    ]
