# Generated by Django 5.2 on 2025-04-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_remove_forms_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='forms', through='forms.FormSubject', to='forms.subject'),
        ),
    ]
