# Generated by Django 5.2 on 2025-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='form_uploads/'),
        ),
        migrations.AlterField(
            model_name='formfieldresponse',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
