# Generated by Django 5.2 on 2025-04-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_formfields_form'),
        ('project', '0002_formfieldresponse_file_alter_formfieldresponse_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldresponse',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_field_res', to='forms.formfields'),
        ),
    ]
