# Generated by Django 5.2 on 2025-04-22 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_formfieldresponse_form_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldresponse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formfieldresponse',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
