# Generated by Django 5.2 on 2025-04-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_formfields_form'),
        ('project', '0004_alter_formfieldresponse_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formsubmission',
            unique_together={('project', 'form')},
        ),
    ]
