# Generated by Django 5.2 on 2025-04-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_formfields_form'),
        ('project', '0005_alter_formsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfieldresponse',
            unique_together={('form_field', 'form_submission')},
        ),
    ]
