# Generated by Django 5.2 on 2025-04-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_formfields_form'),
        ('project', '0006_alter_formfieldresponse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formsubmissions', to='forms.forms'),
        ),
    ]
